# Generated by Django 4.2.7 on 2024-02-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
